extraArgs:
  aws-use-static-instance-list: true

rbac:
  serviceAccount:
    create: false
image:
  repository: "425019299485.dkr.ecr.ap-southeast-1.amazonaws.com/cluster-autoscaler"
  tag: "v1.23.0"
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi
